APP_TITLE = "Анализ рынка недвижимости №13"
PAGE_PADDING = 0
MAX_VISIBLE_ROWS = 10
CSV_EXTENSIONS = ["csv"]
CSV_DIALOG_TITLE = "Выберите файл с данными"

CELL_HEIGHT = 24
HEADER_HEIGHT = 30

TABLE_HEIGHT = CELL_HEIGHT * MAX_VISIBLE_ROWS + HEADER_HEIGHT
